"""Generate homogeneous unicycle2 fleet configs for the encoder-scaling study.

Every fleet size shares one per-robot task definition (dynamics limits, tolerances,
start-offset distribution, sensing radius) so the only quantity that varies is the
number of robots. The goal box grows as sqrt(N/2) to hold goal density -- and
therefore the expected number of visible neighbours -- bounded; with a fixed box the
fleet-level rejection sampler in ``MultiRobotSystem`` cannot place 32 goals at all.

Usage:
    python test/config/generate_fleet_configs.py
"""

from __future__ import annotations

import copy
import sys
from pathlib import Path

import yaml

PROJECT_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(PROJECT_ROOT))

from core.config import validate_system_config  # noqa: E402

TEMPLATE_PATH = PROJECT_ROOT / "test/config/multi_unicycle2_casadi_config.yaml"
OUTPUT_DIR = PROJECT_ROOT / "test/config/study"
FLEET_SIZES = (2, 4, 6, 8, 16, 32)

# Per-robot state-cost block for unicycle2: [x, y, theta, v, omega].
Q_BLOCK = [100.0, 100.0, 10.0, 100.0, 1.0]
BASE_GOAL_HALF_WIDTH = 1.0  # goal_position_bounds default at the reference fleet size
REFERENCE_FLEET_SIZE = 2


def goal_half_width(num_robots: int) -> float:
    return round(BASE_GOAL_HALF_WIDTH * (num_robots / REFERENCE_FLEET_SIZE) ** 0.5, 3)


def build_config(template: dict, num_robots: int) -> dict:
    robot_template = template["robots"][0]
    half_width = goal_half_width(num_robots)

    robot_config = {
        key: value
        for key, value in robot_template["config"].items()
        if key != "goal"  # goals are randomized per episode
    }
    robot_config["randomize_goal"] = True
    robot_config["goal_position_bounds"] = [-half_width, half_width]

    config = {
        key: value
        for key, value in template.items()
        if key not in {"robots", "Q_diag"}
    }
    config["Q_diag"] = Q_BLOCK * num_robots
    # deepcopy per robot: a shallow copy would share the bounds *lists* between
    # entries, and yaml.safe_dump renders repeated objects as &anchor/*alias
    # references instead of writing the values out at each robot.
    config["robots"] = [
        {"system": robot_template["system"], "config": copy.deepcopy(robot_config)}
        for _ in range(num_robots)
    ]
    return config


class _FlowListDumper(yaml.SafeDumper):
    """Renders lists of plain scalars inline, so bound pairs stay on one line.

    Only scalar lists: the robot list holds mappings, and forcing that inline
    collapses the whole fleet into one unreadable wrapped blob.
    """


def _represent_list(dumper: yaml.Dumper, data: list) -> yaml.Node:
    inline = all(isinstance(item, (int, float, str, bool)) for item in data)
    return dumper.represent_sequence("tag:yaml.org,2002:seq", data, flow_style=inline)


_FlowListDumper.add_representer(list, _represent_list)


def format_q_diag(num_robots: int) -> str:
    """Emit Q_diag as one line per robot, matching the hand-written configs.

    The default block style would put all 5*N entries on their own lines (160 of
    them at N=32) and hide the per-robot block structure.
    """
    lines = []
    for robot_idx in range(num_robots):
        values = ", ".join(str(value) for value in Q_BLOCK)
        prefix = "Q_diag: [" if robot_idx == 0 else " " * 9
        suffix = "]" if robot_idx == num_robots - 1 else ","
        lines.append(f"{prefix}{values}{suffix}")
    return "\n".join(lines) + "\n"


def render_config(config: dict, num_robots: int) -> str:
    scalars = {key: value for key, value in config.items() if key not in {"Q_diag", "robots"}}
    return (
        yaml.safe_dump(scalars, sort_keys=False)
        + format_q_diag(num_robots)
        + yaml.dump({"robots": config["robots"]}, Dumper=_FlowListDumper, sort_keys=False)
    )


def main() -> None:
    template = yaml.safe_load(TEMPLATE_PATH.read_text())
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    for num_robots in FLEET_SIZES:
        config = build_config(template, num_robots)
        validate_system_config(system_name="multi_robot", raw_config=config)
        output_path = OUTPUT_DIR / f"unicycle2_fleet_{num_robots:02d}.yaml"
        header = (
            f"# {num_robots}x unicycle2 fleet for the encoder-scaling study.\n"
            f"# Generated by test/config/generate_fleet_configs.py -- do not edit by hand.\n"
            f"# Per-robot task is identical across fleet sizes; only 'robots', 'Q_diag' and\n"
            f"# 'goal_position_bounds' (+-{goal_half_width(num_robots)}) vary with the fleet size.\n"
        )
        output_path.write_text(header + render_config(config, num_robots))
        print(f"wrote {output_path.relative_to(PROJECT_ROOT)} ({num_robots} robots)")


if __name__ == "__main__":
    main()
