"""Generate the density-sweep evaluation configs for the encoder study.

The study evaluates along two separate axes, each changing exactly one quantity:

- fleet size at the training density: ``test/config/study/unicycle2_fleet_NN.yaml``,
  whose workspace grows as sqrt(N) (see generate_fleet_configs.py);
- density at a fixed fleet size: the configs written here.

Every training fleet size uses the same density, so the density a policy was trained on
is one number. Here a few fleet sizes are placed at multiples of it: the workspace half
width at factor f is the training half width divided by sqrt(f). The 1x file therefore
equals the fleet config of the same N and anchors the two axes to each other.

The sweep stops at 3x. The sampler has to place 2N points (starts and goals) at least
d_safe apart; up to 3x (38% of the area blocked by their d_safe disks) that never failed
in 100 episodes for any fleet size up to 32, while at 4x it failed for 20% of 32-robot
episodes and at 5x for 43% of 8-robot episodes. Every config is sampled here before it
is written, so a density that cannot be placed fails now rather than during evaluation.

Usage:
    python test/config/generate_density_configs.py
"""

from __future__ import annotations

import importlib.util
import math
import sys
from pathlib import Path

import yaml

PROJECT_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(PROJECT_ROOT))

from core.config import validate_system_config  # noqa: E402

# Loaded by path: test/config is not a package, and the name "test" would shadow
# the standard library's own module.
_spec = importlib.util.spec_from_file_location(
    "_generate_fleet_configs", Path(__file__).resolve().parent / "generate_fleet_configs.py"
)
_fleet = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_fleet)

TEMPLATE_PATH = _fleet.TEMPLATE_PATH
OUTPUT_DIR = PROJECT_ROOT / "test/config/study/density"
FLEET_SIZES = (4, 8)
DENSITY_FACTORS = (0.25, 0.5, 1.0, 2.0, 3.0)


def density_half_width(num_robots: int, d_safe: float, factor: float) -> float:
    """Half width that puts the fleet at `factor` times the training density."""
    return round(_fleet.goal_half_width(num_robots, d_safe) / math.sqrt(factor), 3)


def factor_label(factor: float) -> str:
    return f"{factor:g}"


def main() -> None:
    template = yaml.safe_load(TEMPLATE_PATH.read_text())
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    d_safe = float(template["d_safe"])
    # The training density, from the reference fleet of generate_fleet_configs.py.
    reference_half_width = _fleet.goal_half_width(_fleet.REFERENCE_FLEET_SIZE, d_safe)
    training_density = _fleet.REFERENCE_FLEET_SIZE / (2.0 * reference_half_width) ** 2

    for num_robots in FLEET_SIZES:
        for factor in DENSITY_FACTORS:
            half_width = density_half_width(num_robots, d_safe, factor)
            config = _fleet.build_config(template, num_robots, half_width=half_width)
            validated = validate_system_config(system_name="multi_robot", raw_config=config)
            mean_visible = _fleet.assert_fleet_is_placeable(validated, num_robots)
            density = num_robots / (2.0 * half_width) ** 2
            # Share of the area covered by the d_safe disks of all 2N starts and goals,
            # the quantity that decides whether the sampler can place them.
            blocked = 2 * num_robots * math.pi * (d_safe / 2.0) ** 2 / (2.0 * half_width) ** 2
            output_path = OUTPUT_DIR / f"unicycle2_n{num_robots:02d}_d{factor_label(factor)}.yaml"
            header = (
                f"# {num_robots}x unicycle2 fleet at {factor:g}x the training density "
                f"(density sweep of the encoder study).\n"
                f"# Generated by test/config/generate_density_configs.py -- do not edit by hand.\n"
                f"# workspace_bounds +-{half_width}: {density:.4f} robots/m^2 "
                f"(training: {training_density:.4f}); d_safe disks of starts and goals\n"
                f"# block {blocked:.0%} of the area; mean visible neighbours ~{mean_visible:.2f}.\n"
            )
            output_path.write_text(header + _fleet.render_config(config, num_robots))
            print(
                f"wrote {output_path.relative_to(PROJECT_ROOT)} ({num_robots} robots, "
                f"{factor:g}x density, +-{half_width}, {blocked:.0%} blocked, "
                f"{mean_visible:.2f} visible neighbours)"
            )


if __name__ == "__main__":
    main()
