# Dataset settings
dataset:
  repo_id: local/double_integrator_casadi_expert
  root: data/lerobot_dataset_double_integrator_casadi

# Policy settings
policy:
  type: act
  device: mps
  
  repo_id: jovaldivieso/double_integrator_casadi_act
  push_to_hub: true

  # Neural network settings (Reduced capacity to prevent overfitting on transit phase)
  dim_model: 32             # Reduced from 64
  dim_feedforward: 128      # Reduced from 256
  n_heads: 4
  n_encoder_layers: 2
  n_decoder_layers: 1
  
  # Action chunking (Tightened to force faster closed-loop correction)
  chunk_size: 4             # Reduced from 24
  n_action_steps: 4         # Reduced from 24
  
  # Explicitly tell LeRobot how to normalize the new ENV state
  normalization_mapping:
    STATE: MIN_MAX
    ENV: MIN_MAX
    ACTION: MIN_MAX
  
  # Split the inputs to satisfy the act architecture
  input_features:
    observation.environment_state:
      shape: [2]
      type: ENV
    observation.state:
      shape: [2]
      type: STATE
      
  output_features:
    action:
      shape: [2]
      type: ACTION

# Training settings
steps: 12500
save_freq: 12500
batch_size: 64
num_workers: 0
save_checkpoint: true
