# Dataset settings
dataset:
  repo_id: local/double_integrator_casadi_expert
  root: data/lerobot_dataset_double_integrator_casadi

# Policy settings
policy:
  type: diffusion
  device: mps
  
  repo_id: jovaldivieso/double_integrator_casadi_diffusion_policy
  push_to_hub: true
  
  # Neural network settings
  down_dims: [32, 64]
  diffusion_step_embed_dim: 16  
  
  # Inference Speed Optimizations
  noise_scheduler_type: DDIM    
  num_inference_steps: 10       
  
  # Horizon & History adjustments
  horizon: 32
  n_action_steps: 16            # Execute 16 steps before re-sampling
  n_obs_steps: 4                # Capture last 4 observation frames
  
  normalization_mapping:
    STATE: MIN_MAX
    ENV: MIN_MAX
    ACTION: MIN_MAX
  
  input_features:
    observation.environment_state:
      shape: [2]
      type: ENV
    observation.state:
      shape: [2]
      type: STATE
      
  output_features:
    action:
      shape: [2]
      type: ACTION

  drop_n_last_frames: 0

# Training settings
steps: 12500
save_freq: 12500
batch_size: 64
num_workers: 0
save_checkpoint: true