# Flow Policy architecture config for learning/train_dagger.py
model:
  policy_type: flow             # options: mlp, flow
  prediction_horizon: 15        # number of future action steps to predict, set to 1 for single-step prediction
  hidden_dims: [256, 256, 256]  # Velocity prediction network hidden layers
  flow:
    num_inference_steps: 10     # Euler integration steps for ODE sampling
  encoder: deepset              # Set to transformer, GNN, etc
  deepset:
    phi_dims: [128, 128]
    rho_dims: [128]
    pool_type: sum              # Can be sum, max, mean
