# Dataset settings
dataset:
  repo_id: local/multi_double_integrator_casadi_expert
  root: data/lerobot_dataset_multi_double_integrator_casadi

# Policy settings
policy:
  type: act
  device: mps

  repo_id: jovaldivieso/multi_double_integrator_casadi_act
  push_to_hub: true

  # Neural network policy settings
  chunk_size: 16
  dim_feedforward: 470
  dim_model: 64
  latent_dim: 24
  n_encoder_layers: 1
  n_heads: 1
  n_vae_encoder_layers: 1
  use_vae: true

  # Action chunking & History adjustments
  n_action_steps: 1
  n_obs_steps: 1            # Must be 1 for LeRobot's ACT implementation

  normalization_mapping:
    STATE: MIN_MAX
    ENV: MIN_MAX
    ACTION: MIN_MAX

  input_features:
    observation.environment_state:
      shape: [8]
      type: ENV
    observation.state:
      shape: [4]
      type: STATE

  output_features:
    action:
      shape: [4]
      type: ACTION

# Training settings
steps: 6000
save_freq: 6000
batch_size: 64
num_workers: 0
save_checkpoint: true
