# Dataset settings
dataset:
  repo_id: local/multi_double_integrator_casadi_expert
  root: data/lerobot_dataset_multi_double_integrator_casadi

# Policy settings
policy:
  type: diffusion
  device: mps

  repo_id: jovaldivieso/multi_double_integrator_casadi_diffusion_policy
  push_to_hub: true

  # Neural network settings
  down_dims: [24, 32]
  diffusion_step_embed_dim: 24

  # Inference speed optimizations
  noise_scheduler_type: DDIM
  num_inference_steps: 20

  # Horizon & history adjustments
  horizon: 32
  n_action_steps: 16
  n_obs_steps: 1

  normalization_mapping:
    STATE: MIN_MAX
    ENV: MIN_MAX
    ACTION: MIN_MAX

  input_features:
    observation.environment_state:
      shape: [8]
      type: ENV
    observation.state:
      shape: [4]
      type: STATE

  output_features:
    action:
      shape: [4]
      type: ACTION

  drop_n_last_frames: 0

# Training settings
steps: 6000
save_freq: 6000
batch_size: 64
num_workers: 0
save_checkpoint: true
