# Policy settings
policy:
  type: act
  device: mps
  
  repo_id: jovaldivieso/unicycle2_casadi_act
  push_to_hub: true

  # Neural network policy settings
  chunk_size: 32
  dim_feedforward: 1024
  dim_model: 128
  latent_dim: 32
  n_encoder_layers: 1
  n_decoder_layers: 1       # Keep this at 1 like default LeRobot's ACT
  n_heads: 1
  n_vae_encoder_layers: 1
  use_vae: true

  # Action chunking & History adjustments
  n_action_steps: 1
  n_obs_steps: 1            # Must be 1 for LeRobot's ACT implementation

  normalization_mapping:
    STATE: MIN_MAX
    ENV: MIN_MAX
    ACTION: MIN_MAX

  input_features:
    observation.environment_state:
      shape: [3]
      type: ENV
    observation.state:
      shape: [2]
      type: STATE

  output_features:
    action:
      shape: [2]
      type: ACTION

# Training settings
steps: 20000
save_freq: 20000
batch_size: 64
num_workers: 0
save_checkpoint: true
