# Dataset settings
dataset:
  repo_id: local/unicycle2_casadi_expert
  root: data/lerobot_dataset_unicycle2_casadi_1786140922

# Policy settings
policy:
  type: diffusion
  device: mps
  
  repo_id: jovaldivieso/unicycle2_casadi_diffusion_policy
  push_to_hub: true
  
  # Neural network settings
  down_dims: [16, 32, 64]           # Reduced from default [512, 1024, 2048]
  diffusion_step_embed_dim: 4       # Reduced from default 128
  
  # Inference Speed Optimizations
  noise_scheduler_type: DDIM    
  num_inference_steps: 20       
  
  # Horizon & History adjustments
  horizon: 16
  n_action_steps: 4             # Execute 4 steps before re-sampling
  n_obs_steps: 3                # Capture observation history
  
  normalization_mapping:
    STATE: MIN_MAX
    ENV: MIN_MAX
    ACTION: MIN_MAX
  
  input_features:
    observation.environment_state:
      shape: [3]
      type: ENV
    observation.state:
      shape: [2]
      type: STATE
      
  output_features:
    action:
      shape: [2]
      type: ACTION

  drop_n_last_frames: 0

# Training settings
steps: 17000
save_freq: 17000
batch_size: 64
num_workers: 0
save_checkpoint: true
